# -*- coding: utf-8 -*-
"""Desigualdades regionales EM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sf4SU8oKi1HWT4BiD9Dyqd-2rt5boRWV
"""

from google.colab import drive
drive.mount('/content/drive')

from google.colab import drive
drive.mount('/content/drive')

import os

folder_path = "/content/drive/MyDrive/ARTICULOS MIOS/ARTICULO EXCESO DEF/"
os.listdir(folder_path)

path_def = "/content/drive/MyDrive/ARTICULOS MIOS/ARTICULO EXCESO DEF/DEFUNCIONES_FUENTE_DEIS_1990_2022_CIFRAS_OFICIALES.zip"

path_pob = "/content/drive/MyDrive/ARTICULOS MIOS/ARTICULO EXCESO DEF/ine_estimaciones-y-proyecciones-2002-2035_base-2017_region_area_tabulados.xlsx"

import zipfile
import pandas as pd

with zipfile.ZipFile(path_def, 'r') as zip_ref:
    print(zip_ref.namelist())

import zipfile
import pandas as pd

with zipfile.ZipFile(path_def, 'r') as zip_ref:
    df = pd.read_csv(
        zip_ref.open("DEFUNCIONES_FUENTE_DEIS_1990_2022_CIFRAS_OFICIALES.csv"),
        encoding="latin-1",
        sep=";",          # DEIS usualmente usa ;
        low_memory=False
    )

df.shape
df.head()
df.columns

df = df[(df["AÑO"] >= 2002) & (df["AÑO"] <= 2022)]

df = df[(df["AÑO"] >= 2002) & (df["AÑO"] <= 2022)]

agg = (
    df
    .groupby(["AÑO", "NOMBRE_REGION"])
    .size()
    .reset_index(name="defunciones")
)

agg.head()
agg.shape

import pandas as pd

path_pob = "/content/drive/MyDrive/ARTICULOS MIOS/ARTICULO EXCESO DEF/ine_estimaciones-y-proyecciones-2002-2035_base-2017_region_area_tabulados.xlsx"

pob = pd.read_excel(path_pob)

excel = pd.ExcelFile(path_pob)
excel.sheet_names

pob.head(10)

pob.iloc[:15, :5]

import pandas as pd

excel = pd.ExcelFile(path_pob)
regiones = excel.sheet_names

lista_pob = []

for region in regiones:
    temp = pd.read_excel(path_pob, sheet_name=region)

    # Extraer años desde fila 0, columnas 1 en adelante
    anios = temp.iloc[0, 1:]

    # Extraer fila "Ambos sexos"
    fila_ambos = temp[temp.iloc[:,0] == "Ambos sexos"]

    poblacion = fila_ambos.iloc[0, 1:]

    df_temp = pd.DataFrame({
        "AÑO": anios.values.astype(int),
        "NOMBRE_REGION": region.replace("Región de ", "").strip(),
        "poblacion": poblacion.values.astype(int)
    })

    lista_pob.append(df_temp)

pob_long = pd.concat(lista_pob, ignore_index=True)

pob_long = pob_long[(pob_long["AÑO"] >= 2002) & (pob_long["AÑO"] <= 2022)]

pob_long.shape
pob_long.head()

sorted(agg["NOMBRE_REGION"].unique())

agg = agg[agg["NOMBRE_REGION"] != "Ignorada"]

import unicodedata

def limpiar_region(nombre):
    nombre = nombre.replace("De ", "")
    nombre = nombre.replace("Del ", "")
    nombre = nombre.replace("Metropolitana de Santiago", "Metropolitana")
    nombre = nombre.replace("Magallanes y de La Antártica Chilena", "Magallanes")
    nombre = nombre.replace("Aisén del Gral. C. Ibáñez del Campo", "Aysén")
    nombre = nombre.replace("Libertador B. O'Higgins", "O'Higgins")
    nombre = nombre.replace("Bíobío", "Biobío")

    # normalizar acentos
    nombre = unicodedata.normalize("NFKD", nombre).encode("ascii", "ignore").decode("utf-8")

    return nombre.strip()

agg["NOMBRE_REGION"] = agg["NOMBRE_REGION"].apply(limpiar_region)
pob_long["NOMBRE_REGION"] = pob_long["NOMBRE_REGION"].apply(limpiar_region)

sorted(agg["NOMBRE_REGION"].unique())

sorted(pob_long["NOMBRE_REGION"].unique())

data = agg.merge(pob_long, on=["AÑO", "NOMBRE_REGION"], how="left")

data.isnull().sum()
data.shape

import numpy as np

data["log_poblacion"] = np.log(data["poblacion"])

# Variable tiempo continua
data["t"] = data["AÑO"] - 2002

base = data[data["AÑO"] <= 2019].copy()
pandemia = data[data["AÑO"] >= 2020].copy()

import statsmodels.api as sm
import statsmodels.formula.api as smf

modelo = smf.glm(
    formula="defunciones ~ t * C(NOMBRE_REGION)",
    data=base,
    family=sm.families.Poisson(),
    offset=base["log_poblacion"]
).fit()

print(modelo.summary())

import statsmodels.api as sm
import statsmodels.formula.api as smf

modelo_nb = smf.glm(
    formula="defunciones ~ t * C(NOMBRE_REGION)",
    data=base,
    family=sm.families.NegativeBinomial(),
    offset=base["log_poblacion"]
).fit()

print(modelo_nb.summary())

import statsmodels.api as sm
import patsy

# Fórmula sin offset
formula = "defunciones ~ t * C(NOMBRE_REGION)"

y, X = patsy.dmatrices(formula, base, return_type='dataframe')

# Agregar offset manualmente
offset = base["log_poblacion"]

modelo_nb = sm.NegativeBinomial(
    y,
    X,
    offset=offset
).fit()

print(modelo_nb.summary())

pandemia["pred_esperado"] = modelo.predict(
    pandemia,
    offset=pandemia["log_poblacion"]
)

pandemia["exceso"] = pandemia["defunciones"] - pandemia["pred_esperado"]

pandemia["tasa_exceso"] = (
    pandemia["exceso"] / pandemia["poblacion"]
) * 100000

pandemia["porcentaje_exceso"] = (
    pandemia["exceso"] / pandemia["pred_esperado"]
) * 100

pandemia.head()

resumen = (
    pandemia
    .groupby("NOMBRE_REGION")
    .agg(
        defunciones_obs=("defunciones", "sum"),
        defunciones_esp=("pred_esperado", "sum"),
        exceso_total=("exceso", "sum"),
        poblacion_total=("poblacion", "sum")
    )
    .reset_index()
)

resumen["tasa_exceso_2020_2022"] = (
    resumen["exceso_total"] / resumen["poblacion_total"]
) * 100000

resumen["porcentaje_exceso_2020_2022"] = (
    resumen["exceso_total"] / resumen["defunciones_esp"]
) * 100

resumen = resumen.sort_values(
    "tasa_exceso_2020_2022",
    ascending=False
)

resumen



rango = resumen["tasa_exceso_2020_2022"].max() - resumen["tasa_exceso_2020_2022"].min()
razon = resumen["tasa_exceso_2020_2022"].max() / resumen["tasa_exceso_2020_2022"].min()
cv = resumen["tasa_exceso_2020_2022"].std() / resumen["tasa_exceso_2020_2022"].mean()

print("Rango absoluto:", rango)
print("Razón max/min:", razon)
print("Coeficiente de variación:", cv)

def gini(x):
    x = np.sort(x)
    n = len(x)
    index = np.arange(1, n+1)
    return (2 * np.sum(index * x) / (n * np.sum(x))) - (n + 1) / n

gini_valor = gini(resumen["tasa_exceso_2020_2022"].values)
print("Índice de Gini:", gini_valor)

resumen_validacion = (
    pandemia
    .groupby("NOMBRE_REGION")
    .agg(
        defunciones_obs=("defunciones", "sum"),
        defunciones_esp=("pred_esperado", "sum"),
        poblacion_total=("poblacion", "sum")
    )
    .reset_index()
)

resumen_validacion["tasa_observada"] = (
    resumen_validacion["defunciones_obs"] /
    resumen_validacion["poblacion_total"]
) * 100000

resumen_validacion["tasa_esperada"] = (
    resumen_validacion["defunciones_esp"] /
    resumen_validacion["poblacion_total"]
) * 100000

resumen_validacion["diferencia_tasas"] = (
    resumen_validacion["tasa_observada"]
    - resumen_validacion["tasa_esperada"]
)

resumen_validacion = resumen_validacion.sort_values(
    "diferencia_tasas",
    ascending=False
)

resumen_validacion

resumen_validacion.merge(
    resumen[["NOMBRE_REGION", "tasa_exceso_2020_2022"]],
    on="NOMBRE_REGION"
)

df["edad_anios"] = np.where(
    df["EDAD_TIPO"] == "Años", df["EDAD_CANT"],
    np.where(
        df["EDAD_TIPO"] == "Meses", df["EDAD_CANT"] / 12,
        np.where(
            df["EDAD_TIPO"] == "Días", df["EDAD_CANT"] / 365,
            np.nan
        )
    )
)

df["grupo_edad"] = pd.cut(
    df["edad_anios"],
    bins=[-1, 64, 79, 150],
    labels=["<65", "65-79", "80+"]
)

df["grupo_edad"].value_counts()

df["EDAD_TIPO"].unique()

df[["EDAD_TIPO","EDAD_CANT"]].head(10)

df["edad_anios"] = np.where(
    df["EDAD_TIPO"] == 1, df["EDAD_CANT"],
    np.where(
        df["EDAD_TIPO"] == 2, df["EDAD_CANT"] / 12,
        np.where(
            df["EDAD_TIPO"] == 3, df["EDAD_CANT"] / 365,
            np.where(
                df["EDAD_TIPO"] == 4, df["EDAD_CANT"] / (365*24),
                np.nan
            )
        )
    )
)

df["edad_anios"].describe()

df["grupo_edad"] = pd.cut(
    df["edad_anios"],
    bins=[-1, 64, 79, 150],
    labels=["<65", "65-79", "80+"]
)

df["grupo_edad"].value_counts()

df["grupo_edad2"] = pd.cut(
    df["edad_anios"],
    bins=[-1, 64, 150],
    labels=["<65", "65+"]
)

df["grupo_edad2"].value_counts()

agg_edad = (
    df[(df["AÑO"] >= 2002) & (df["AÑO"] <= 2022)]
    .groupby(["AÑO", "NOMBRE_REGION", "grupo_edad2"])
    .size()
    .reset_index(name="defunciones")
)

excel = pd.ExcelFile(path_pob)
print(excel.sheet_names)

temp = pd.read_excel(path_pob, sheet_name="Arica y Parinacota")
temp.head(40)

import os

folder_path = "/content/drive/MyDrive/ARTICULOS MIOS/ARTICULO EXCESO DEF/"
os.listdir(folder_path)

path_pob_edad = "/content/drive/MyDrive/ARTICULOS MIOS/ARTICULO EXCESO DEF/ine grupo etario.xlsx"

excel_edad = pd.ExcelFile(path_pob_edad)
excel_edad.sheet_names

pob_edad_test = pd.read_excel(path_pob_edad, sheet_name="Arica y Parinacota")
pob_edad_test.head(15)

lista_pob_edad = []

for region in regiones:
    temp = pd.read_excel(path_pob_edad, sheet_name=region)

    # Extraer años (fila 0)
    anios = temp.iloc[0, 1:]
    anios = anios[~anios.isna()].astype(int)

    # Extraer filas
    fila_0_14 = temp[temp.iloc[:,0] == "0-14 años"].iloc[0, 1:len(anios)+1]
    fila_15_64 = temp[temp.iloc[:,0] == "15-64 años"].iloc[0, 1:len(anios)+1]
    fila_65mas = temp[temp.iloc[:,0] == "65 y más años"].iloc[0, 1:len(anios)+1]

    pob_menor65 = fila_0_14.values + fila_15_64.values
    pob_65mas = fila_65mas.values

    df_temp1 = pd.DataFrame({
        "AÑO": anios.values,
        "NOMBRE_REGION": region,
        "grupo_edad2": "<65",
        "poblacion": pob_menor65
    })

    df_temp2 = pd.DataFrame({
        "AÑO": anios.values,
        "NOMBRE_REGION": region,
        "grupo_edad2": "65+",
        "poblacion": pob_65mas
    })

    lista_pob_edad.append(df_temp1)
    lista_pob_edad.append(df_temp2)

pob_edad_long = pd.concat(lista_pob_edad, ignore_index=True)

# Filtrar periodo
pob_edad_long = pob_edad_long[
    (pob_edad_long["AÑO"] >= 2002) &
    (pob_edad_long["AÑO"] <= 2022)
]

pob_edad_long.head()
pob_edad_long.shape

temp.iloc[:,0].unique()

lista_pob_edad = []

for region in regiones:
    temp = pd.read_excel(path_pob_edad, sheet_name=region, header=None)

    # La fila 0 contiene los años
    anios = temp.iloc[0, 1:]
    anios = anios[~anios.isna()].astype(int)

    # Buscar filas por texto
    fila_0_14 = temp[temp.iloc[:,0] == "0-14 años"].iloc[0, 1:len(anios)+1]
    fila_15_64 = temp[temp.iloc[:,0] == "15-64 años"].iloc[0, 1:len(anios)+1]
    fila_65mas = temp[temp.iloc[:,0] == "65 y más años"].iloc[0, 1:len(anios)+1]

    pob_menor65 = fila_0_14.values + fila_15_64.values
    pob_65mas = fila_65mas.values

    df_temp1 = pd.DataFrame({
        "AÑO": anios.values,
        "NOMBRE_REGION": region,
        "grupo_edad2": "<65",
        "poblacion": pob_menor65
    })

    df_temp2 = pd.DataFrame({
        "AÑO": anios.values,
        "NOMBRE_REGION": region,
        "grupo_edad2": "65+",
        "poblacion": pob_65mas
    })

    lista_pob_edad.append(df_temp1)
    lista_pob_edad.append(df_temp2)

pob_edad_long = pd.concat(lista_pob_edad, ignore_index=True)

# Filtrar 2002–2022
pob_edad_long = pob_edad_long[
    (pob_edad_long["AÑO"] >= 2002) &
    (pob_edad_long["AÑO"] <= 2022)
]

pob_edad_long.shape
pob_edad_long.head()

pob_edad_long.shape

pob_edad_long["NOMBRE_REGION"] = pob_edad_long["NOMBRE_REGION"].apply(limpiar_region)

agg_edad = (
    df[(df["AÑO"] >= 2002) & (df["AÑO"] <= 2022)]
    .groupby(["AÑO", "NOMBRE_REGION", "grupo_edad2"])
    .size()
    .reset_index(name="defunciones")
)

agg_edad["NOMBRE_REGION"] = agg_edad["NOMBRE_REGION"].apply(limpiar_region)

agg_edad.head()
agg_edad.shape

pob_edad_long["AÑO"].min(), pob_edad_long["AÑO"].max()

pob_edad_long["AÑO"].unique()

pob_edad_long = pob_edad_long[
    (pob_edad_long["AÑO"] >= 2002) &
    (pob_edad_long["AÑO"] <= 2022)
].copy()

print(pob_edad_long.shape)

print(agg_edad.shape)

len(pob_edad_long["NOMBRE_REGION"].unique())

sorted(pob_edad_long["NOMBRE_REGION"].unique())

pob_edad_long.groupby("NOMBRE_REGION").size()

del pob_edad_long

lista_pob_edad = []

for region in regiones:
    temp = pd.read_excel(path_pob_edad, sheet_name=region, header=None)

    anios = temp.iloc[0, 1:]
    anios = anios[~anios.isna()].astype(int)

    fila_0_14 = temp[temp.iloc[:,0] == "0-14 años"].iloc[0, 1:len(anios)+1]
    fila_15_64 = temp[temp.iloc[:,0] == "15-64 años"].iloc[0, 1:len(anios)+1]
    fila_65mas = temp[temp.iloc[:,0] == "65 y más años"].iloc[0, 1:len(anios)+1]

    pob_menor65 = fila_0_14.values + fila_15_64.values
    pob_65mas = fila_65mas.values

    df_temp1 = pd.DataFrame({
        "AÑO": anios.values,
        "NOMBRE_REGION": region,
        "grupo_edad2": "<65",
        "poblacion": pob_menor65
    })

    df_temp2 = pd.DataFrame({
        "AÑO": anios.values,
        "NOMBRE_REGION": region,
        "grupo_edad2": "65+",
        "poblacion": pob_65mas
    })

    lista_pob_edad.append(df_temp1)
    lista_pob_edad.append(df_temp2)

pob_edad_long = pd.concat(lista_pob_edad, ignore_index=True)

pob_edad_long = pob_edad_long[
    (pob_edad_long["AÑO"] >= 2002) &
    (pob_edad_long["AÑO"] <= 2022)
].copy()

print(pob_edad_long.shape)

agg_edad = (
    df[(df["AÑO"] >= 2002) & (df["AÑO"] <= 2022)]
    .groupby(["AÑO", "NOMBRE_REGION", "grupo_edad2"])
    .size()
    .reset_index(name="defunciones")
)

agg_edad["NOMBRE_REGION"] = agg_edad["NOMBRE_REGION"].apply(limpiar_region)

print(agg_edad.shape)

print(sorted(agg_edad["NOMBRE_REGION"].unique()))
print(sorted(pob_edad_long["NOMBRE_REGION"].unique()))

agg_edad = agg_edad[agg_edad["NOMBRE_REGION"] != "Ignorada"]

import unicodedata

def limpiar_region(nombre):
    nombre = str(nombre)
    nombre = nombre.replace("Región de ", "")
    nombre = nombre.replace("Del ", "")
    nombre = nombre.replace("De ", "")
    nombre = nombre.replace("Metropolitana de Santiago", "Metropolitana")
    nombre = nombre.replace("Magallanes y de La Antártica Chilena", "Magallanes")
    nombre = nombre.replace("Aisén del Gral. C. Ibáñez del Campo", "Aysen")
    nombre = nombre.replace("Libertador B. O'Higgins", "O'Higgins")

    # eliminar acentos
    nombre = unicodedata.normalize("NFKD", nombre).encode("ascii", "ignore").decode("utf-8")

    return nombre.strip()

agg_edad["NOMBRE_REGION"] = agg_edad["NOMBRE_REGION"].apply(limpiar_region)
pob_edad_long["NOMBRE_REGION"] = pob_edad_long["NOMBRE_REGION"].apply(limpiar_region)

print(sorted(agg_edad["NOMBRE_REGION"].unique()))
print(sorted(pob_edad_long["NOMBRE_REGION"].unique()))

data_edad = agg_edad.merge(
    pob_edad_long,
    on=["AÑO", "NOMBRE_REGION", "grupo_edad2"],
    how="left"
)

print(data_edad.isnull().sum())
print(data_edad.shape)

data_edad["poblacion"] = pd.to_numeric(data_edad["poblacion"], errors="raise")
data_edad["poblacion"] = data_edad["poblacion"].astype(float)

data_edad["log_poblacion"] = np.log(data_edad["poblacion"].values)
data_edad["t"] = data_edad["AÑO"] - 2002

print(data_edad["poblacion"].dtype)

base_edad = data_edad[data_edad["AÑO"] <= 2019]
pandemia_edad = data_edad[data_edad["AÑO"] >= 2020]

base_edad.shape

import statsmodels.api as sm
import statsmodels.formula.api as smf

modelo_edad = smf.glm(
    formula="defunciones ~ t * C(NOMBRE_REGION) + C(grupo_edad2)",
    data=base_edad,
    family=sm.families.Poisson(),
    offset=base_edad["log_poblacion"]
).fit()

print(modelo_edad.summary())

import statsmodels.api as sm
import statsmodels.formula.api as smf

base_edad = data_edad[data_edad["AÑO"] <= 2019].copy()

modelo_nb_edad = smf.negativebinomial(
    formula="defunciones ~ t * C(NOMBRE_REGION) + C(grupo_edad2)",
    data=base_edad,
    offset=base_edad["log_poblacion"]
).fit(maxiter=200)

print(modelo_nb_edad.summary())

# Predecir esperadas 2020–2022
pandemia_edad["pred_esperado"] = modelo_nb_edad.predict(
    pandemia_edad,
    offset=pandemia_edad["log_poblacion"]
)

# Calcular exceso
pandemia_edad["exceso"] = pandemia_edad["defunciones"] - pandemia_edad["pred_esperado"]

# Agregar por región
resumen_edad = (
    pandemia_edad
    .groupby("NOMBRE_REGION")
    .agg(
        def_obs=("defunciones", "sum"),
        def_esp=("pred_esperado", "sum"),
        poblacion=("poblacion", "sum")
    )
    .reset_index()
)

resumen_edad["exceso_total"] = resumen_edad["def_obs"] - resumen_edad["def_esp"]
resumen_edad["tasa_exceso_ajustada"] = (
    resumen_edad["exceso_total"] / resumen_edad["poblacion"] * 100000
)

resumen_edad = resumen_edad.sort_values("tasa_exceso_ajustada", ascending=False)

resumen_edad

rango_adj = resumen_edad["tasa_exceso_ajustada"].max() - resumen_edad["tasa_exceso_ajustada"].min()
razon_adj = resumen_edad["tasa_exceso_ajustada"].max() / resumen_edad["tasa_exceso_ajustada"].min()
cv_adj = resumen_edad["tasa_exceso_ajustada"].std() / resumen_edad["tasa_exceso_ajustada"].mean()

rango_adj, razon_adj, cv_adj

def gini(x):
    x = np.sort(x)
    n = len(x)
    return (2 * np.sum((np.arange(1, n+1) * x)) / (n * np.sum(x))) - (n+1)/n

gini_adj = gini(resumen_edad["tasa_exceso_ajustada"].values)
gini_adj

!pip install geopandas

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Crear matriz región-año
pivot = pandemia_edad.pivot_table(
    values="exceso",
    index="NOMBRE_REGION",
    columns="AÑO",
    aggfunc="sum"
)

X = np.arange(pivot.columns.min(), pivot.columns.max()+1)
Y = np.arange(len(pivot.index))

X, Y = np.meshgrid(X, Y)
Z = pivot.values

fig = plt.figure(figsize=(10,7))
ax = fig.add_subplot(111, projection='3d')

surf = ax.plot_surface(X, Y, Z, cmap='viridis')

ax.set_xlabel("Año")
ax.set_ylabel("Región")
ax.set_zlabel("Exceso")

fig.colorbar(surf, shrink=0.5, aspect=5)
plt.show()

# Calcular tasa ajustada por región-año
pivot_tasa = (
    pandemia_edad
    .groupby(["NOMBRE_REGION", "AÑO"])
    .agg(
        exceso=("exceso", "sum"),
        poblacion=("poblacion", "sum")
    )
    .reset_index()
)

pivot_tasa["tasa"] = pivot_tasa["exceso"] / pivot_tasa["poblacion"] * 100000

# Pivot
pivot_tasa = pivot_tasa.pivot(index="NOMBRE_REGION", columns="AÑO", values="tasa")

# Ordenar regiones por promedio 2020–2022
pivot_tasa["promedio"] = pivot_tasa.mean(axis=1)
pivot_tasa = pivot_tasa.sort_values("promedio", ascending=False)
pivot_tasa = pivot_tasa.drop(columns="promedio")

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

X = np.arange(pivot_tasa.columns.min(), pivot_tasa.columns.max()+1)
Y = np.arange(len(pivot_tasa.index))

X, Y = np.meshgrid(X, Y)
Z = pivot_tasa.values

fig = plt.figure(figsize=(11,8))
ax = fig.add_subplot(111, projection='3d')

surf = ax.plot_surface(
    X, Y, Z,
    cmap="plasma",
    edgecolor="white",
    linewidth=0.4,
    antialiased=True
)

ax.set_xlabel("Año", labelpad=10)
ax.set_ylabel("Región", labelpad=10)
ax.set_zlabel("Tasa exceso (×100.000)", labelpad=10)

ax.set_yticks(np.arange(len(pivot_tasa.index)))
ax.set_yticklabels(pivot_tasa.index)

ax.view_init(elev=30, azim=-120)

fig.colorbar(surf, shrink=0.6, aspect=10)

plt.title("Exceso de Mortalidad No COVID-19 Ajustado por Edad\nChile 2020–2022")
plt.tight_layout()
plt.show()

!wget https://naturalearth.s3.amazonaws.com/50m_cultural/ne_50m_admin_1_states_provinces.zip
!unzip ne_50m_admin_1_states_provinces.zip

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,8))

sns.heatmap(
    pivot_tasa,
    cmap="plasma",
    linewidths=0.5,
    linecolor="white",
    cbar_kws={"label": "Tasa exceso (×100.000)"}
)

plt.title("Exceso de Mortalidad No COVID-19 Ajustado por Edad\nChile 2020–2022")
plt.xlabel("Año")
plt.ylabel("Región")

plt.tight_layout()
plt.show()

import geopandas as gpd

shp = gpd.read_file("ne_50m_admin_1_states_provinces.shp")

# Filtrar Chile
chile_reg = shp[shp["admin"] == "Chile"]

chile_reg.head()

shp.columns

chile_reg = shp[shp["iso_a2"] == "CL"]

len(chile_reg)

sorted(chile_reg["name"].unique())

!wget https://raw.githubusercontent.com/caracena/chile-geojson/master/regiones.geojson

!wget -O chile_regiones.geojson https://raw.githubusercontent.com/datasets/geo-admin1-us/master/data/chile.geojson

!wget https://geodata.ucdavis.edu/gadm/gadm4.1/json/gadm41_CHL_1.json

import geopandas as gpd

chile_reg = gpd.read_file("gadm41_CHL_1.json")

len(chile_reg)

sorted(chile_reg["NAME_1"].unique())

mapping = {
    "AricayParinacota": "Arica y Parinacota",
    "Tarapacá": "Tarapaca",
    "Antofagasta": "Antofagasta",
    "Atacama": "Atacama",
    "Coquimbo": "Coquimbo",
    "Valparaíso": "Valparaiso",
    "SantiagoMetropolitan": "Metropolitana",
    "LibertadorGeneralBernardoO'Hi": "O'Higgins",
    "Maule": "Maule",
    "Ñuble": "Nuble",
    "Bío-Bío": "Biobio",
    "Araucanía": "La Araucania",
    "LosRíos": "Los Rios",
    "LosLagos": "Los Lagos",
    "AyséndelGeneralIbañezdelCam": "Aysen",
    "MagallanesyAntárticaChilena": "Magallanes"
}

chile_reg["region_clean"] = chile_reg["NAME_1"].map(mapping)

chile_reg["region_clean"].isnull().sum()

mapa = chile_reg.merge(
    resumen_edad,
    left_on="region_clean",
    right_on="NOMBRE_REGION",
    how="left"
)

mapa.isnull().sum()

import matplotlib.pyplot as plt
import mapclassify

# Clasificación por cuantiles
scheme = mapclassify.Quantiles(
    mapa["tasa_exceso_ajustada"],
    k=5
)

fig, ax = plt.subplots(figsize=(7,12))

mapa.plot(
    column="tasa_exceso_ajustada",
    cmap="plasma",
    scheme="Quantiles",
    k=5,
    linewidth=0.6,
    edgecolor="black",
    legend=True,
    legend_kwds={
        "title": "Tasa exceso ajustada\n(×100.000)",
        "loc": "lower left"
    },
    ax=ax
)

ax.set_title(
    "Exceso de Mortalidad No COVID-19 Ajustado por Edad\nChile 2020–2022",
    fontsize=13,
    pad=15
)

ax.axis("off")

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import matplotlib as mpl

fig, ax = plt.subplots(figsize=(6,12))

# Paleta epidemiológica
cmap = plt.cm.viridis  # alternativa: 'cividis', 'inferno', 'coolwarm'

# Normalización continua
norm = mpl.colors.Normalize(
    vmin=mapa["tasa_exceso_ajustada"].min(),
    vmax=mapa["tasa_exceso_ajustada"].max()
)

mapa.plot(
    column="tasa_exceso_ajustada",
    cmap=cmap,
    linewidth=0.5,
    edgecolor="black",
    ax=ax
)

# Barra continua elegante
sm = mpl.cm.ScalarMappable(cmap=cmap, norm=norm)
sm._A = []

cbar = fig.colorbar(sm, ax=ax, fraction=0.03, pad=0.02)
cbar.set_label("Tasa de exceso ajustada (×100.000)", rotation=90)

ax.set_title(
    "Exceso de Mortalidad No COVID-19 Ajustado por Edad\nChile 2020–2022",
    fontsize=12,
    pad=15
)

ax.set_facecolor("white")
ax.axis("off")

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import matplotlib as mpl

fig, ax = plt.subplots(figsize=(5,11))

cmap = plt.cm.cividis

norm = mpl.colors.Normalize(
    vmin=mapa["tasa_exceso_ajustada"].min(),
    vmax=mapa["tasa_exceso_ajustada"].max()
)

mapa.plot(
    column="tasa_exceso_ajustada",
    cmap=cmap,
    linewidth=0.4,
    edgecolor="black",
    ax=ax
)

# Ajustar límites para eliminar espacio vacío
ax.set_xlim(mapa.total_bounds[0], mapa.total_bounds[2])
ax.set_ylim(mapa.total_bounds[1], mapa.total_bounds[3])

# Barra horizontal
sm = mpl.cm.ScalarMappable(cmap=cmap, norm=norm)
sm._A = []

cbar = fig.colorbar(
    sm,
    ax=ax,
    orientation="horizontal",
    fraction=0.04,
    pad=0.02
)

cbar.set_label("Tasa de exceso ajustada (×100.000)")

ax.set_title(
    "Exceso de mortalidad no COVID-19 ajustado por edad\nChile 2020–2022",
    fontsize=11
)

ax.axis("off")

plt.tight_layout()
plt.show()

from google.colab import drive
drive.mount('/content/drive')

ruta = "/content/drive/MyDrive/ARTICULOS MIOS/ARTICULO EXCESO DEF/"

import os
os.listdir(ruta)

import pandas as pd
import zipfile

ruta = "/content/drive/MyDrive/ARTICULOS MIOS/ARTICULO EXCESO DEF/"

# Descomprimir
with zipfile.ZipFile(ruta + "DEFUNCIONES_FUENTE_DEIS_1990_2022_CIFRAS_OFICIALES.zip") as z:
    z.extractall(ruta)

# Ver archivos extraídos
import os
os.listdir(ruta)

data_def = pd.read_csv(
    ruta + "DEFUNCIONES_FUENTE_DEIS_1990_2022_CIFRAS_OFICIALES.csv",
    encoding="latin1",
    sep=";"
)

data_def.head()
data_def.columns

data_def.to_csv(ruta + "DEIS_limpio_utf8.csv", index=False)

import numpy as np

def convertir_edad(row):
    if row["EDAD_TIPO"] == 1:
        return row["EDAD_CANT"]
    elif row["EDAD_TIPO"] == 2:
        return row["EDAD_CANT"] / 12
    elif row["EDAD_TIPO"] == 3:
        return row["EDAD_CANT"] / 365
    elif row["EDAD_TIPO"] == 4:
        return row["EDAD_CANT"] / (365*24)
    else:
        return np.nan

data_def["edad_anios"] = data_def.apply(convertir_edad, axis=1)

data_def = data_def[
    (data_def["AÑO"] >= 2002) &
    (data_def["AÑO"] <= 2022)
]

data_def["grupo_edad2"] = data_def["edad_anios"].apply(
    lambda x: "<65" if x < 65 else "65+"
)

data_agg = (
    data_def
    .groupby(["AÑO", "NOMBRE_REGION", "grupo_edad2"])
    .size()
    .reset_index(name="defunciones")
)

data_agg.shape

data = data_agg.merge(
    pob_edad_long,
    on=["AÑO", "NOMBRE_REGION", "grupo_edad2"],
    how="left"
)

data_agg["NOMBRE_REGION"].unique()

data_agg = data_agg[data_agg["NOMBRE_REGION"] != "Ignorada"]

import pandas as pd

pob_dict = pd.read_excel(
    ruta + "ine grupo etario.xlsx",
    sheet_name=None
)

pob_lista = []

for region, df in pob_dict.items():

    # Buscar filas clave
    fila_014 = df[df.iloc[:,0] == "0-14 años"].index[0]
    fila_1564 = df[df.iloc[:,0] == "15-64 años"].index[0]
    fila_65mas = df[df.iloc[:,0] == "65 y más años"].index[0]

    # Extraer años (columnas desde 2002 en adelante)
    anios = df.columns[1:22]  # 2002–2022

    for i, anio in enumerate(anios):

        pob_014 = df.iloc[fila_014, i+1]
        pob_1564 = df.iloc[fila_1564, i+1]
        pob_65 = df.iloc[fila_65mas, i+1]

        pob_lista.append({
            "AÑO": int(anio),
            "NOMBRE_REGION": region,
            "grupo_edad2": "<65",
            "poblacion": pob_014 + pob_1564
        })

        pob_lista.append({
            "AÑO": int(anio),
            "NOMBRE_REGION": region,
            "grupo_edad2": "65+",
            "poblacion": pob_65
        })

pob_edad_long = pd.DataFrame(pob_lista)

pob_edad_long.shape

pob_edad_long["NOMBRE_REGION"] = (
    pob_edad_long["NOMBRE_REGION"]
    .str.replace("á","a")
    .str.replace("é","e")
    .str.replace("í","i")
    .str.replace("ó","o")
    .str.replace("ú","u")
    .str.replace("ñ","n")
)

data = data_agg.merge(
    pob_edad_long,
    on=["AÑO", "NOMBRE_REGION", "grupo_edad2"],
    how="left"
)

data.isna().sum()

sorted(data_agg["NOMBRE_REGION"].unique())

sorted(pob_edad_long["NOMBRE_REGION"].unique())

import unicodedata

def limpiar(texto):
    texto = str(texto)
    texto = unicodedata.normalize('NFKD', texto)
    texto = texto.encode('ascii', errors='ignore').decode('utf-8')
    texto = texto.replace("De ", "")
    texto = texto.replace("Del ", "")
    texto = texto.replace("Metropolitana de Santiago", "Metropolitana")
    texto = texto.replace("Del Libertador B. O'Higgins", "O'Higgins")
    texto = texto.replace("De Aisen del Gral. C. Ibanez del Campo", "Aysen")
    texto = texto.replace("De Magallanes y de La Antartica Chilena", "Magallanes")
    texto = texto.replace("Del Biobio", "Biobio")
    texto = texto.replace("De La Araucania", "La Araucania")
    texto = texto.replace("De Los Rios", "Los Rios")
    texto = texto.replace("De Los Lagos", "Los Lagos")
    texto = texto.replace("De Tarapaca", "Tarapaca")
    texto = texto.replace("De Valparaiso", "Valparaiso")
    texto = texto.replace("De Antofagasta", "Antofagasta")
    texto = texto.replace("De Arica y Parinacota", "Arica y Parinacota")
    texto = texto.replace("De Atacama", "Atacama")
    texto = texto.replace("De Coquimbo", "Coquimbo")
    texto = texto.replace("De Nuble", "Nuble")
    texto = texto.replace("De Maule", "Maule")
    texto = texto.strip()
    return texto

data_agg["region_clean"] = data_agg["NOMBRE_REGION"].apply(limpiar)
pob_edad_long["region_clean"] = pob_edad_long["NOMBRE_REGION"].apply(limpiar)

sorted(data_agg["region_clean"].unique())

sorted(pob_edad_long["region_clean"].unique())

data = data_agg.merge(
    pob_edad_long,
    on=["AÑO", "grupo_edad2", "region_clean"],
    how="left"
)

data.isna().sum()

sorted(pob_edad_long["AÑO"].unique())

sorted(data_agg["AÑO"].unique())

data_agg.groupby(["AÑO", "grupo_edad2"]).size()

data[data["poblacion"].isna()][["AÑO", "region_clean", "grupo_edad2"]]

set(data_agg["region_clean"]) - set(pob_edad_long["region_clean"])

set(pob_edad_long["region_clean"]) - set(data_agg["region_clean"])

mapeo_regiones = {
    "Aisen del Gral. C. Ibanez del Campo": "Aysen",
    "Magallanes y de La Antartica Chilena": "Magallanes",
    "Libertador B. O'Higgins": "O'Higgins"
}

# Aplicar en la base INE (la que tiene nombres largos)
pob_edad_long["region_clean"] = pob_edad_long["region_clean"].replace(mapeo_regiones)

set(data_agg["region_clean"]) - set(pob_edad_long["region_clean"])

set()

set(data_agg["region_clean"]) - set(pob_edad_long["region_clean"])

sorted(pob_edad_long["region_clean"].unique())

data = data_agg.merge(
    pob_edad_long[["AÑO", "grupo_edad2", "region_clean", "poblacion"]],
    on=["AÑO", "grupo_edad2", "region_clean"],
    how="left"
)

data.isna().sum()

data_agg.head()

map_regiones = {
    "Aisen del Gral. C. Ibanez del Campo": "Aysen",
    "Libertador B. O'Higgins": "O'Higgins",
    "Magallanes y de La Antartica Chilena": "Magallanes"
}

data_agg["region_clean"] = data_agg["region_clean"].replace(map_regiones)

set(data_agg["region_clean"]) - set(pob_edad_long["region_clean"])

data = pd.merge(
    data_agg,
    pob_edad_long,
    on=["AÑO", "grupo_edad2", "region_clean"],
    how="left"
)

data.isna().sum()

data_pre = data[data["AÑO"] <= 2019].copy()
data_pre["t"] = data_pre["AÑO"] - 2002
data_pre["t2"] = data_pre["t"]**2

import statsmodels.api as sm
import statsmodels.formula.api as smf
import numpy as np

data_pre["log_poblacion"] = np.log(data_pre["poblacion"])

modelo_lineal = smf.glm(
    formula="defunciones ~ C(region_clean) + C(grupo_edad2) + t",
    data=data_pre,
    family=sm.families.Poisson(),
    offset=data_pre["log_poblacion"]
).fit()

modelo_cuad = smf.glm(
    formula="defunciones ~ C(region_clean) + C(grupo_edad2) + t + t2",
    data=data_pre,
    family=sm.families.Poisson(),
    offset=data_pre["log_poblacion"]
).fit()

data_post = data[data["AÑO"] >= 2020].copy()
data_post["t"] = data_post["AÑO"] - 2002
data_post["t2"] = data_post["t"]**2
data_post["log_poblacion"] = np.log(data_post["poblacion"])

data_post["pred_lineal"] = modelo_lineal.predict(data_post)
data_post["pred_cuad"] = modelo_cuad.predict(data_post)

resumen_sens = data_post.groupby("region_clean").agg(
    obs=("defunciones","sum"),
    esp_lineal=("pred_lineal","sum"),
    esp_cuad=("pred_cuad","sum"),
    poblacion=("poblacion","sum")
).reset_index()

resumen_sens["exceso_lineal"] = resumen_sens["obs"] - resumen_sens["esp_lineal"]
resumen_sens["exceso_cuad"] = resumen_sens["obs"] - resumen_sens["esp_cuad"]

resumen_sens["tasa_lineal"] = resumen_sens["exceso_lineal"] / resumen_sens["poblacion"] * 100000
resumen_sens["tasa_cuad"] = resumen_sens["exceso_cuad"] / resumen_sens["poblacion"] * 100000

resumen_sens[["tasa_lineal","tasa_cuad"]].describe()

correlacion = resumen_sens["tasa_lineal"].corr(resumen_sens["tasa_cuad"])
correlacion

modelo_nb = smf.glm(
    formula="defunciones ~ C(region_clean) + C(grupo_edad2) + t",
    data=data_pre,
    family=sm.families.NegativeBinomial(),
    offset=data_pre["log_poblacion"]
).fit()

pred_lineal = modelo_lineal.get_prediction(data_post)

pred_lineal_summary = pred_lineal.summary_frame(alpha=0.05)

data_post["esp_lineal"] = pred_lineal_summary["mean"]
data_post["esp_lineal_li"] = pred_lineal_summary["mean_ci_lower"]
data_post["esp_lineal_ls"] = pred_lineal_summary["mean_ci_upper"]

pred_nb = modelo_nb.get_prediction(data_post)
pred_summary = pred_nb.summary_frame(alpha=0.05)

data_post["esp_nb"] = pred_summary["mean"]
data_post["esp_nb_low"] = pred_summary["mean_ci_lower"]
data_post["esp_nb_high"] = pred_summary["mean_ci_upper"]

pred_cuad = modelo_cuad.get_prediction(data_post)

pred_cuad_summary = pred_cuad.summary_frame(alpha=0.05)

data_post["esp_cuad"] = pred_cuad_summary["mean"]
data_post["esp_cuad_li"] = pred_cuad_summary["mean_ci_lower"]
data_post["esp_cuad_ls"] = pred_cuad_summary["mean_ci_upper"]

resumen_ic = data_post.groupby("region_clean").agg(
    obs=("defunciones","sum"),
    esp=("esp_lineal","sum"),
    li=("esp_lineal_li","sum"),
    ls=("esp_lineal_ls","sum"),
    poblacion=("poblacion","sum")
).reset_index()

resumen_ic["exceso"] = resumen_ic["obs"] - resumen_ic["esp"]
resumen_ic["exceso_li"] = resumen_ic["obs"] - resumen_ic["ls"]
resumen_ic["exceso_ls"] = resumen_ic["obs"] - resumen_ic["li"]

resumen_ic["tasa"] = resumen_ic["exceso"] / resumen_ic["poblacion"] * 100000
resumen_ic["tasa_li"] = resumen_ic["exceso_li"] / resumen_ic["poblacion"] * 100000
resumen_ic["tasa_ls"] = resumen_ic["exceso_ls"] / resumen_ic["poblacion"] * 100000

modelo_lineal.pearson_chi2 / modelo_lineal.df_resid

family=sm.families.NegativeBinomial()

import statsmodels.api as sm
import statsmodels.formula.api as smf

modelo_nb = smf.negativebinomial(
    formula="defunciones ~ C(region_clean) + C(grupo_edad2) + t",
    data=data_pre,
    offset=data_pre["log_poblacion"]
).fit()

modelo_nb.summary()

pred_nb = modelo_nb.get_prediction(data_post)
pred_nb_summary = pred_nb.summary_frame()

pred_nb_summary.columns

data_post["esp_nb"] = pred_nb_summary["predicted"]
data_post["esp_nb_li"] = pred_nb_summary["ci_lower"]
data_post["esp_nb_ls"] = pred_nb_summary["ci_upper"]

resumen_nb = data_post.groupby("region_clean").agg(
    obs=("defunciones","sum"),
    esp=("esp_nb","sum"),
    li=("esp_nb_li","sum"),
    ls=("esp_nb_ls","sum"),
    poblacion=("poblacion","sum")
).reset_index()

resumen_nb["exceso"] = resumen_nb["obs"] - resumen_nb["esp"]
resumen_nb["exceso_li"] = resumen_nb["obs"] - resumen_nb["ls"]
resumen_nb["exceso_ls"] = resumen_nb["obs"] - resumen_nb["li"]

resumen_nb["tasa"] = resumen_nb["exceso"] / resumen_nb["poblacion"] * 100000
resumen_nb["tasa_li"] = resumen_nb["exceso_li"] / resumen_nb["poblacion"] * 100000
resumen_nb["tasa_ls"] = resumen_nb["exceso_ls"] / resumen_nb["poblacion"] * 100000

data_post.shape

pred_nb = modelo_nb.get_prediction(data_post)
pred_nb_summary = pred_nb.summary_frame()

data_post["esp_nb"] = pred_nb_summary["predicted"]
data_post["esp_nb_li"] = pred_nb_summary["ci_lower"]
data_post["esp_nb_ls"] = pred_nb_summary["ci_upper"]

pred_nb_summary.head()

data_post["check"] = pred_nb_summary["predicted"] * data_post["poblacion"]
data_post[["check","defunciones"]].head()

data_post = data_post.reset_index(drop=True)

pred_nb = modelo_nb.get_prediction(data_post)
pred_nb_summary = pred_nb.summary_frame()

data_post["esp_nb"] = pred_nb_summary["predicted"]
data_post["esp_nb_li"] = pred_nb_summary["ci_lower"]
data_post["esp_nb_ls"] = pred_nb_summary["ci_upper"]

data_post[["defunciones","esp_nb"]].head()

data_post["esp_nb"] = pred_nb_summary["predicted"] * data_post["poblacion"]
data_post["esp_nb_li"] = pred_nb_summary["ci_lower"] * data_post["poblacion"]
data_post["esp_nb_ls"] = pred_nb_summary["ci_upper"] * data_post["poblacion"]

data_post[["defunciones","esp_nb"]].head()

resumen_nb = data_post.groupby("region_clean").agg(
    obs=("defunciones","sum"),
    esp=("esp_nb","sum"),
    li=("esp_nb_li","sum"),
    ls=("esp_nb_ls","sum"),
    poblacion=("poblacion","sum")
).reset_index()

resumen_nb["exceso"] = resumen_nb["obs"] - resumen_nb["esp"]
resumen_nb["exceso_li"] = resumen_nb["obs"] - resumen_nb["ls"]
resumen_nb["exceso_ls"] = resumen_nb["obs"] - resumen_nb["li"]

resumen_nb["tasa"] = resumen_nb["exceso"] / resumen_nb["poblacion"] * 100000
resumen_nb["tasa_li"] = resumen_nb["exceso_li"] / resumen_nb["poblacion"] * 100000
resumen_nb["tasa_ls"] = resumen_nb["exceso_ls"] / resumen_nb["poblacion"] * 100000

print(resumen_nb.head())

obs_total = resumen_nb["obs"].sum()
esp_total = resumen_nb["esp"].sum()
li_total = resumen_nb["li"].sum()
ls_total = resumen_nb["ls"].sum()

exceso_total = obs_total - esp_total
exceso_li_total = obs_total - ls_total
exceso_ls_total = obs_total - li_total

print("Exceso total:", exceso_total)
print("IC95%:", exceso_li_total, "-", exceso_ls_total)

pob_total = resumen_nb["poblacion"].sum()

tasa_total = exceso_total / pob_total * 100000
tasa_li_total = exceso_li_total / pob_total * 100000
tasa_ls_total = exceso_ls_total / pob_total * 100000

print("Tasa por 100.000:", tasa_total)
print("IC95% tasa:", tasa_li_total, "-", tasa_ls_total)

data_pre_crudo = data[data["AÑO"] <= 2019].copy()
data_pre_crudo["t"] = data_pre_crudo["AÑO"] - 2002
data_pre_crudo["log_poblacion"] = np.log(data_pre_crudo["poblacion"])

modelo_nb_crudo = smf.negativebinomial(
    formula="defunciones ~ C(region_clean) + t",
    data=data_pre_crudo,
    offset=data_pre_crudo["log_poblacion"]
).fit()

modelo_nb_crudo.summary()

data_post_crudo = data[data["AÑO"] >= 2020].copy()
data_post_crudo["t"] = data_post_crudo["AÑO"] - 2002
data_post_crudo["log_poblacion"] = np.log(data_post_crudo["poblacion"])
data_post_crudo = data_post_crudo.reset_index(drop=True)

pred_nb_crudo = modelo_nb_crudo.get_prediction(data_post_crudo)
pred_nb_crudo_summary = pred_nb_crudo.summary_frame()

data_post_crudo["esp"] = pred_nb_crudo_summary["predicted"] * data_post_crudo["poblacion"]
data_post_crudo["li"] = pred_nb_crudo_summary["ci_lower"] * data_post_crudo["poblacion"]
data_post_crudo["ls"] = pred_nb_crudo_summary["ci_upper"] * data_post_crudo["poblacion"]

resumen_crudo = data_post_crudo.groupby("region_clean").agg(
    obs=("defunciones","sum"),
    esp=("esp","sum"),
    li=("li","sum"),
    ls=("ls","sum"),
    poblacion=("poblacion","sum")
).reset_index()

obs_total = resumen_crudo["obs"].sum()
esp_total = resumen_crudo["esp"].sum()
li_total = resumen_crudo["li"].sum()
ls_total = resumen_crudo["ls"].sum()

exceso_total = obs_total - esp_total
exceso_li_total = obs_total - ls_total
exceso_ls_total = obs_total - li_total

print("Exceso crudo:", exceso_total)
print("IC95%:", exceso_li_total, "-", exceso_ls_total)

data_crudo = (
    data
    .groupby(["AÑO", "region_clean"])
    .agg(
        defunciones=("defunciones","sum"),
        poblacion=("poblacion","sum")
    )
    .reset_index()
)

pob_total = resumen_crudo["poblacion"].sum()

tasa_total = exceso_total / pob_total * 100000
tasa_li_total = exceso_li_total / pob_total * 100000
tasa_ls_total = exceso_ls_total / pob_total * 100000

print("Tasa cruda:", tasa_total)
print("IC95% tasa:", tasa_li_total, "-", tasa_ls_total)

data_pre_crudo = data_crudo[data_crudo["AÑO"] <= 2019].copy()
data_pre_crudo["t"] = data_pre_crudo["AÑO"] - 2002
data_pre_crudo["log_poblacion"] = np.log(data_pre_crudo["poblacion"])

modelo_nb_crudo = smf.negativebinomial(
    formula="defunciones ~ C(region_clean) + t",
    data=data_pre_crudo,
    offset=data_pre_crudo["log_poblacion"]
).fit()

modelo_nb_crudo.summary()

data_post_crudo = data_crudo[data_crudo["AÑO"] >= 2020].copy()
data_post_crudo["t"] = data_post_crudo["AÑO"] - 2002
data_post_crudo["log_poblacion"] = np.log(data_post_crudo["poblacion"])
data_post_crudo = data_post_crudo.reset_index(drop=True)

pred_nb_crudo = modelo_nb_crudo.get_prediction(data_post_crudo)
pred_nb_crudo_summary = pred_nb_crudo.summary_frame()

data_post_crudo["esp"] = pred_nb_crudo_summary["predicted"] * data_post_crudo["poblacion"]
data_post_crudo["li"] = pred_nb_crudo_summary["ci_lower"] * data_post_crudo["poblacion"]
data_post_crudo["ls"] = pred_nb_crudo_summary["ci_upper"] * data_post_crudo["poblacion"]

obs_total = data_post_crudo["defunciones"].sum()
esp_total = data_post_crudo["esp"].sum()
li_total = data_post_crudo["li"].sum()
ls_total = data_post_crudo["ls"].sum()

exceso_total = obs_total - esp_total
exceso_li_total = obs_total - ls_total
exceso_ls_total = obs_total - li_total

print("Exceso crudo:", exceso_total)
print("IC95%:", exceso_li_total, "-", exceso_ls_total)